//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class casino_sicherheitsvorfall
    {
        public int PK_Sicherheitsvorfall { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<System.TimeSpan> Uhrzeit { get; set; }
        public string Ort { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> FK_Gast { get; set; }
        public Nullable<int> FK_Mitarbeiter { get; set; }
        public Nullable<int> FK_Raum { get; set; }
        public string Massnahme { get; set; }
    
        public virtual casino_gast casino_gast { get; set; }
        public virtual casino_mitarbeiter casino_mitarbeiter { get; set; }
        public virtual casino_raeume casino_raeume { get; set; }
    }
}
