//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class casino_schicht
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public casino_schicht()
        {
            this.casino_mitarbeiter = new HashSet<casino_mitarbeiter>();
        }
    
        public int PK_Schicht { get; set; }
        public Nullable<System.TimeSpan> Startzeit { get; set; }
        public Nullable<System.TimeSpan> Endzeit { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<casino_mitarbeiter> casino_mitarbeiter { get; set; }
    }
}
