//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class casino_gast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public casino_gast()
        {
            this.casino_sicherheitsvorfall = new HashSet<casino_sicherheitsvorfall>();
            this.casino_transaktion = new HashSet<casino_transaktion>();
        }
    
        public int PK_Gast { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string Ausweisnummer { get; set; }
        public Nullable<System.DateTime> Registrierungsdatum { get; set; }
        public Nullable<bool> VIP { get; set; }
        public string Adresse { get; set; }
        public Nullable<bool> Sperrstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<casino_sicherheitsvorfall> casino_sicherheitsvorfall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<casino_transaktion> casino_transaktion { get; set; }
    }
}
