//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class casino_mitarbeiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public casino_mitarbeiter()
        {
            this.casino_sicherheitsvorfall = new HashSet<casino_sicherheitsvorfall>();
            this.casino_schicht = new HashSet<casino_schicht>();
        }
    
        public int PK_Mitarbeiter { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string Geschlecht { get; set; }
        public string Adresse { get; set; }
        public string Telefonnummer { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> Einstellungsdatum { get; set; }
        public Nullable<int> FK_Rolle { get; set; }
        public Nullable<int> FK_Raum { get; set; }
    
        public virtual casino_raeume casino_raeume { get; set; }
        public virtual casino_rollen casino_rollen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<casino_sicherheitsvorfall> casino_sicherheitsvorfall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<casino_schicht> casino_schicht { get; set; }
    }
}
