//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class g5_6it23Entities1 : DbContext
    {
        public g5_6it23Entities1()
            : base("name=g5_6it23Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<casino_gast> casino_gast { get; set; }
        public virtual DbSet<casino_kameraueberwachung> casino_kameraueberwachung { get; set; }
        public virtual DbSet<casino_mitarbeiter> casino_mitarbeiter { get; set; }
        public virtual DbSet<casino_raeume> casino_raeume { get; set; }
        public virtual DbSet<casino_rollen> casino_rollen { get; set; }
        public virtual DbSet<casino_schicht> casino_schicht { get; set; }
        public virtual DbSet<casino_sicherheitsvorfall> casino_sicherheitsvorfall { get; set; }
        public virtual DbSet<casino_spiel> casino_spiel { get; set; }
        public virtual DbSet<casino_transaktion> casino_transaktion { get; set; }
    }
}
