//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class casino_spiel
    {
        public int PK_Spiel { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<decimal> MinEinsatz { get; set; }
        public Nullable<decimal> MaxEinsatz { get; set; }
        public Nullable<System.DateTime> LetzteWartung { get; set; }
        public string Status { get; set; }
        public Nullable<int> FK_Raum { get; set; }
    
        public virtual casino_raeume casino_raeume { get; set; }
    }
}
