//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class kameraueberwachung
    {
        public int PK_Kameraueberwachung { get; set; }
        public string Standort { get; set; }
        public string Aufzeichnungsraum { get; set; }
        public Nullable<int> Speicherdauer { get; set; }
        public Nullable<System.TimeSpan> Uhrzeit { get; set; }
        public Nullable<int> FK_Raum { get; set; }
    
        public virtual raeume raeume { get; set; }
    }
}
