//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class mitarbeiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mitarbeiter()
        {
            this.sicherheitsvorfall = new HashSet<sicherheitsvorfall>();
            this.schicht = new HashSet<schicht>();
        }
    
        public int PK_Mitarbeiter { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string Geschlecht { get; set; }
        public string Adresse { get; set; }
        public string Telefonnummer { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> Einstellungsdatum { get; set; }
        public Nullable<int> FK_Rolle { get; set; }
        public Nullable<int> FK_Raum { get; set; }
    
        public virtual rollen rollen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sicherheitsvorfall> sicherheitsvorfall { get; set; }
        public virtual raeume raeume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schicht> schicht { get; set; }
    }
}
