//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class casinoEntities1 : DbContext
    {
        public casinoEntities1()
            : base("name=casinoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gast> gast { get; set; }
        public virtual DbSet<kameraueberwachung> kameraueberwachung { get; set; }
        public virtual DbSet<mitarbeiter> mitarbeiter { get; set; }
        public virtual DbSet<raeume> raeume { get; set; }
        public virtual DbSet<rollen> rollen { get; set; }
        public virtual DbSet<schicht> schicht { get; set; }
        public virtual DbSet<sicherheitsvorfall> sicherheitsvorfall { get; set; }
        public virtual DbSet<spiel> spiel { get; set; }
        public virtual DbSet<transaktion> transaktion { get; set; }
    }
}
