//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaktion
    {
        public int PK_Transaktion { get; set; }
        public Nullable<int> FK_Gast { get; set; }
        public Nullable<decimal> Betrag { get; set; }
        public Nullable<System.DateTime> Zeitpunkt { get; set; }
        public string Zahlungsmittel { get; set; }
    
        public virtual gast gast { get; set; }
    }
}
